#!/usr/bin/env python3
"""
Brain Index Generator — Hermes Memory Tier 2 Index
=====================================================
Generates brain/index.json from filesystem brain directory.

Usage:
  python3 gen-brain-index.py [--force-regenerate]

The index maps topics to files, enabling selective fetch by Hermes
without loading entire brain into context.
"""

import json
import os
import re
from datetime import datetime, timedelta
from pathlib import Path

BRAIN_DIR = Path(os.path.expanduser("~/Desktop/Niumination/brain"))
INDEX_PATH = BRAIN_DIR / "index.json"
ARCHIVE_INDEX_PATH = BRAIN_DIR / "archive" / "_index.md"
MAX_FILES = 500
DAYS_STALE = 30

# Topic inference rules — map path patterns → topic tags
TOPIC_PATTERNS = {
    r"docs/.*": ["documentation", "docs"],
    r"infra/.*": ["infrastructure", "ops"],
    r"logs/.*": ["logs", "operations"],
    r"ops/.*": ["operations", "infrastructure"],
    r"projects/.*": ["projects", "development"],
    r"scripts/.*": ["scripts", "automation"],
    r"templates/.*": ["templates", "reference"],
    r"inbox/.*": ["inbox", "pending", "daily"],
    r"resources/.*": ["resources", "reference"],
    r"30-Resources/.*": ["resources", "reference"],
    r"scripts/hooks/.*": ["git", "hooks", "automation"],
    r"scripts/.*-*" : ["scripts", "automation"],
    r"scripts/.*\.sh": ["scripts", "shell", "automation"],
    r"scripts/.*\.py": ["scripts", "python", "automation"],
    r"Backup.*Firefox": ["browser", "firefox", "tabs"],
    r"AGENTS\.md": ["dox", "documentation"],
    r"BACKLOG\.md": ["dox", "planning"],
    r"_index\.md": ["index", "reference"],
    r"paparan-sekda\.md": ["presentation", "sekda", "gayor"],
}

SKIP_DIRS = {".git", ".obsidian", "archive"}


def infer_topics(file_path: str) -> list:
    """Infer topic tags from file path name/contents."""
    # Start with path-based inference
    topics = set()
    for pattern, tags in TOPIC_PATTERNS.items():
        if re.search(pattern, file_path):
            topics.update(tags)
    
    # Additional heuristics from filename
    filename = os.path.basename(file_path).lower()
    if "leak" in filename or "found" in filename:
        topics.update(["security", "audit", "leak"])
    if "daily" in filename:
        topics.update(["daily", "log"])
    if "sekda" in filename or "paparan" in filename:
        topics.update(["gayor", "presentation"])
    if "repair" in filename or "fix" in filename:
        topics.update(["fix", "repair"])
    
    # Fallback: use base filename without extension
    if not topics:
        name_no_ext = Path(filename).stem
        if name_no_ext:
            topics.add(name_no_ext)
    
    return sorted(topics)


def generate_summary(file_path: str, max_length: int = 200) -> str:
    """Generate a brief summary of file contents (first 200 chars of text)."""
    try:
        with open(file_path, "r", encoding="utf-8", errors="replace") as f:
            text = f.read(max_length * 3)
        # Clean whitespace
        text = " ".join(text.split())
        if len(text) > max_length:
            text = text[:max_length] + "..."
        return text
    except Exception as e:
        return f"[error reading file: {e}]"


def generate_index(force_regenerate: bool = False) -> dict:
    """Scan brain directory and generate index JSON."""
    index = {
        "generated_at": datetime.now().isoformat(),
        "version": "1.0",
        "total_files": 0,
        "files": [],
        "topic_index": {},
        "notes": "Auto-generated by gen-brain-index.py"
    }

    file_count = 0
    
    # Walk brain directory, skip .git and .obsidian
    for root, dirs, files in os.walk(BRAIN_DIR):
        # Skip unwanted directories
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        
        for filename in files:
            # Skip unwanted files
            if filename == ".DS_Store":
                continue
            if filename.endswith(".lock"):
                continue
            if filename.endswith(".json") and filename != "index.json":
                # Skip other JSON files (like curator state) — they're not brain notes
                continue
            
            file_path = Path(root) / filename
            rel_path = file_path.relative_to(BRAIN_DIR)
            rel_path_str = str(rel_path).replace(os.sep, "/")
            
            # Skip index files themselves
            if filename == "index.json" and str(rel_path) == "index.json":
                continue
            
            # Get file metadata
            try:
                stat = file_path.stat()
                file_size = stat.st_size
                mtime = datetime.fromtimestamp(stat.st_mtime)
            except Exception:
                continue
            
            # Infer topics
            topics = infer_topics(rel_path_str)
            if not topics:
                topics = [Path(filename).stem]
            
            # Generate summary
            summary = generate_summary(str(file_path))
            
            # Determine tier
            if "archive" in str(rel_path):
                tier = "cold"
            else:
                tier = "warm"
            
            # File entry
            file_entry = {
                "path": f"brain/{rel_path_str}",
                "filename": filename,
                "topics": topics,
                "size_bytes": file_size,
                "mtime": mtime.isoformat(),
                "tier": tier,
                "summary": summary,
                "relevance_score": 1.0,  # Will be adjusted later if needed
                "last_accessed": None  # Unknown — will be updated on access
            }
            
            index["files"].append(file_entry)
            file_count += 1
            
            # Index by topics
            for topic in topics:
                if topic not in index["topic_index"]:
                    index["topic_index"][topic] = []
                index["topic_index"][topic].append(f"brain/{rel_path_str}")
    
    index["total_files"] = file_count
    index["tier_counts"] = {
        "warm": sum(1 for f in index["files"] if f["tier"] == "warm"),
        "cold": sum(1 for f in index["files"] if f["tier"] == "cold")
    }
    
    return index


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Generate brain index")
    parser.add_argument("--force-regenerate", action="store_true",
                       help="Regenerate index regardless of existing")
    args = parser.parse_args()
    
    # Check if index exists and is fresh
    if INDEX_PATH.exists() and not args.force_regenerate:
        try:
            with open(INDEX_PATH, "r") as f:
                existing = json.load(f)
            mtime = datetime.fromisoformat(existing["generated_at"])
            age = datetime.now() - mtime
            if age < timedelta(hours=1):
                print(f"Index is fresh (age: {age}) — skipping regenerate")
                return
            print(f"Index is {age.days} days old — regenerating")
        except Exception:
            pass
    
    print(f"Scanning {BRAIN_DIR}...")
    index = generate_index(args.force_regenerate)
    
    # Write index
    with open(INDEX_PATH, "w") as f:
        json.dump(index, f, indent=2, ensure_ascii=False)
    
    print(f"Generated index with {index['total_files']} files")
    print(f"  Warm tier: {index['tier_counts']['warm']} files")
    print(f"  Cold tier: {index['tier_counts']['cold']} files")
    print(f"  Topics: {len(index['topic_index'])} unique topics")
    print(f"  Index saved to: {INDEX_PATH}")
    
    # Print top topics
    topic_counts = sorted(
        [(t, len(files)) for t, files in index["topic_index"].items()],
        key=lambda x: -x[1]
    )
    print("\nTop 15 topics:")
    for topic, count in topic_counts[:15]:
        print(f"  {topic}: {count}")


if __name__ == "__main__":
    main()
